services:
  anqr:
    image: postgres:17
    restart: always
    container_name: anqr
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: anqr
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
